# Generated by Django 4.0.6 on 2022-12-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_auto_20221215_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_balance',
            field=models.IntegerField(default=0, verbose_name='Leave Balance'),
        ),
    ]
